name: ClaudiaMcKenzie
favicon: null
layout_spectrum: 0.65811
typography_spectrum: 0.94661
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#636363'
    - '#191512'
    - '#f4f4f4'
    - '#9a9a9a'
    - '#d4d4d4'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
